### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [yagihashib/TC359_TwitterBootstrap#1]
It looks like this project is using Bootstrap 2.3.2, which is no longer supported. Can you update to [the latest version (3.3.2)](http://getbootstrap.com/) and repush to GitHub and Heroku? Please let me know when this is done.

**Comment by yagihashib** [comment]
Hi Chris, I just changed to bootstrap version 3.3.2 on both this project
and for the DRY Sinatra.

Let me know if there are any more problems.

**Comment by chrisvfritz** [comment]
It looks like a little bit more updating will be necessary, as the grid system in v3 works a little differently than in previous versions. The [documentation here](http://getbootstrap.com/css/#grid) explains it.

I'm also not seeing a showcase for the DRY Sinatra project in Codekwondo yet. Are you sure you've created a showcase and checked all the criteria?

**Comment by chrisvfritz** [comment]
:+1: Better. Thanks!
